name: Testing & Linters

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Setup Secrets
      run: |
        echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > app/google-services.json
      env:
        GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
      
    - name: Run Tests and Linters
      run: ./gradlew test
