name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Copy services into place
      run: |
        echo "$GOOGLE_SERVICES_JSON_BASE64" | base64 --decode > app/google-services.json
      env:
        GOOGLE_SERVICES_JSON_BASE64: ${{ secrets.GOOGLE_SERVICES_JSON }}
      
    - name: Build with Gradle
      run: ./gradlew build
