name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Copy services into place
      run: |
        echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 --decode | tee google-services.json
        mv google-services.json app/google-services.json
      
    - name: Build with Gradle
      run: ./gradlew build
